version: "3.8"

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbuniclass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - uniclassnet

  tomee:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_URL=jdbc:postgresql://postgres:5432/dbuniclass
    networks:
      - uniclassnet

volumes:
  pgdata:

# networks è importante per gestire e isolare il traffico dei servizi dei container
networks:
  uniclassnet:
